url: "https://s-iguchi09.github.io"

plugins:
  - jekyll-sitemap

collections:
  articles_en:
    output: true
    permalink: /articles/:name/
  articles_ja:
    output: true
    permalink: /ja/articles/:name/
  apps_en:
    output: true
    permalink: /apps/:name/
  apps_ja:
    output: true
    permalink: /ja/apps/:name/