name: Manual Dispatch

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run manual dispatch
        run: echo "手動実行されました。"
